from enum import Enum

class WorkflowStage(str, Enum):

    QUEUED = "QUEUED"

    VIDEO_PROCESSING = "VIDEO_PROCESSING"

    PARALLEL_PROCESSING = "PARALLEL_PROCESSING"

    SUMMARY_PROCESSING = "SUMMARY_PROCESSING"

    COMPLETED = "COMPLETED"

    FAILED = "FAILED"


class ServiceStatus(str, Enum):

    PENDING = "PENDING"

    QUEUED = "QUEUED"

    COMPLETED = "COMPLETED"

    FAILED = "FAILED"